"""Write images and YOLO-format labels in the standard dataset layout.

Layout produced under ``<out>``::

    images/train/  images/val/
    labels/train/  labels/val/
    data.yaml

YOLO label format — one ``.txt`` per image, one line per object::

    0 <cx> <cy> <w> <h>     # class 0 (plate); all values normalised 0–1

Note the coordinate change: the compositor returns the box as ``[x, y, w, h]``
with a **top-left** origin (matching the README §2 contract); YOLO wants the
**centre** ``(cx, cy)``, so we convert here.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

SPLITS = ("train", "val")
_DATA_YAML = """\
# Auto-generated by plate_redactor.generator — YOLO dataset descriptor.
path: {path}
train: images/train
val: images/val
names:
  0: plate
"""


def prepare_dirs(out_root: str | Path) -> Path:
    """Create the images/labels train/val tree and return the root path."""
    root = Path(out_root)
    for sub in ("images", "labels"):
        for split in SPLITS:
            (root / sub / split).mkdir(parents=True, exist_ok=True)
    return root


def write_data_yaml(out_root: str | Path) -> Path:
    """Write ``data.yaml`` and return its path."""
    root = Path(out_root)
    path = root / "data.yaml"
    path.write_text(_DATA_YAML.format(path=str(root)), encoding="utf-8")
    return path


def _clamp(v: float) -> float:
    return min(1.0, max(0.0, v))


def write_sample(out_root: str | Path, split: str, name: str,
                 image: Image.Image, bbox_xywh: list[float]) -> tuple[Path, Path]:
    """Write one image + its YOLO label.

    Args:
        bbox_xywh: ``[x, y, w, h]`` normalised, top-left origin (as produced by
            the compositor). Converted to YOLO centre coordinates here.

    Returns:
        ``(image_path, label_path)``.
    """
    if split not in SPLITS:
        raise ValueError(f"split must be one of {SPLITS}, got {split!r}")
    root = Path(out_root)

    img_path = root / "images" / split / f"{name}.jpg"
    image.convert("RGB").save(img_path, "JPEG", quality=92)

    x, y, w, h = bbox_xywh
    cx, cy = x + w / 2.0, y + h / 2.0
    line = f"0 {_clamp(cx):.6f} {_clamp(cy):.6f} {_clamp(w):.6f} {_clamp(h):.6f}\n"
    label_path = root / "labels" / split / f"{name}.txt"
    label_path.write_text(line, encoding="utf-8")
    return img_path, label_path
